on:
  issue_comment:
    types: [created]
name: Pull requests comment
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: PullRequestHandler
        uses: Ash258/Scoop-GithubActions@master-win
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITH_EMAIL: cabera.jakub@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
