on:
  pull_request:
    types: [opened]
name: Pull requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: PullRequestHandler
        uses: Ash258/Scoop-GithubActions@master-win
        env:
          GITH_EMAIL: cabera.jakub@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
